
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exp4?useSSL=false&serverTimezone=UTC
    username: root
    password: jk200497
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-handlers-package: org.exp4.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

