spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exp4
    username: root
    password: jk200497
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwtSecret: zFBU1saYTdOV2zCS64jECZE4NR87nnDCSKUxohu7WcOl2dBhrAj3JTtmoHjisAkGsHwAPw3OP9TNAEIk8SD81w
  jwtExpirationInMs: 86400000

server:
  port: 8081