import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import React from "react";
//
// const geistSans = localFont({
//   src: "../../public/fonts/GeistVF.woff",
//   //src: "@/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../../public/fonts/GeistMonoVF.woff",
//  // src: "@/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "20220669Jiake",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
          className={`antialiased h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
